### ISSUE TITLE
Výběr kvality

### ISSUE THREAD

**Issue by pschonmann** [72ka/plugin.video.dmd-czech.playtvak#3]
Ahoj, postrádám možnost ihned pustit video a ne pokaždé zvolit kvalitu. Šlo by udělat nastavení doplnku kde vyberu kvalitu a ta se vzdy spusti po zvoleni videa ?
Moc díky.

**Comment by 72ka** [comment]
Ahoj, Samozřejmě to jde a mám to v plánu (už od začátku). Ale zatím nejsou lidi :) Momentálně velmi volným tempem pracuji na novém doplňku pro iDNES.tv, takže počítám že až ho někdy dokončím, tak bych se do toho pustím. Je to opravdu jen o čase.

**Comment by jose1711** [comment]
asi to nie je uplne idealne ale aspon jeden klik usetri: https://github.com/jose1711/plugin.video.dmd-czech.playtvak/tree/autoquality

**Comment by 72ka** [comment]
Ahoj,  díky. Já se na to chystám už přes rok.. ale nejsou lidi :( Klidně můžeš udělat pull request. Já to testnu a schválím. Super

**Comment by 72ka** [comment]
Jo jen jeden comment. Koukám do kódu a mám pocit, že tohle selže v případě zapnuté autokvality na high u pořadu, který je pouze v middle. A taková videa bohužel na playtvaku jsou... už nevím kde, ale narazil jsem na ně, u hodně starých pořadů.

**Comment by jose1711** [comment]
dik, doplnim to a urobim PR
