### ISSUE TITLE
Nová ikona

### ISSUE THREAD

**Issue by MarhyCZ** [72ka/plugin.video.dmd-czech.playtvak#4]
Dobrý den,
multimediální centrum je primárně na sledování obsahu, ale taky jeho procházení by mělo být hezkým zážitkem. Napadlo mě redesignovat ikony všech doplňků z tohoto úžasného repozitáře Kodi CZ&SK najednou, aby měli koherentní design, a moderním, hravým vzhledem i vzbudili chuť méně zkušenějším uživatelům je nainstalovat a prozkoumávat :) Návrhy jsem chtěl poslat na jednotlivé github stránky každého doplňku.

Zvolil jsem čtvercová loga, protože průhledná jsou někdy vidět hezky na tmavém skinu a někdy zase jen na světlém. Pozadí je vždy jedna barva či velice lehký gradient. Obsah ikony je vždy 80% na šířku či výšku podle poměru stran. Oficiální wiki Kodi říká, že doplněk by měl mít ikonu 512x512 pixelů, ale to bylo psané v dobách 1080p a když už teď 4K televizory nejsou úplnou raritou, a tyto ikony mají tak jednoduchou grafiku, že mají velice malou velikost na disku, napadlo mě jít rovnou na 1024x1024px.

### Návrhy

Na mém GitHubu se můžete kouknout na ostatní navrhované ikony ve [složce s 2048px návrhy](https://github.com/MarhyCZ/marhycz.github.io/tree/master/kodi-czsk-icons/navrhy)

Případně pár návrhů v jednom obrázku: 
https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/czsknahled.png
_____________________________________________________________________________________________

### Ikona Playtvak.cz
Pro Playtvak.cz a Slow.tv jsem vytvořil 2 návrhy. Jeden se přesně řídil dle nejnovějšího logotypu playtvak.cz (late 2016) a druhý byla moje volná stylizace, která se snažila zbavit nudného bílého pozadí a působit více hravým dojmem při zachování gradientu z loga playtvak.cz. 

#### Logotyp
2048px návrh ikony Playtvak.cz podle logotypu je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/navrhy/playtvak.png)

1024px verze ikony Playtvak.cz podle logotypu pro Kodi je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/1024/playtvak.png).

#### Stylizovaná verze MarhyCZ
2048px návrh ikony Playtvak.cz ve stylizované verzi je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/navrhy/playtvak2.png)

1024px verze ikony Playtvak.cz ve stylizované verzi pro Kodi je [zde](https://github.com/MarhyCZ/marhycz.github.io/blob/master/kodi-czsk-icons/1024/playtvak2.png).

Vybral bych pro playtvak.cz a Slow tv stejnou verzi ikon.

**Comment by Vasek79** [comment]
Dobrý den,
add-on Playtvak poslední dobou, asi čtrnáct dní nefunguje - nepřehrává videa.
Add-on se spustí, načte se menu, načtou se i názvy a náhledy/obrázky videí, ale po odkliknutí kteréhokoliv videa se po chvíli zobrazí hlášení o chybě. Nejsem zrovna doma, takže log nemám k dipozici. Později mohu dodat...
Podle diskuze na www.xbmc-kodi.cz to nejede ani na Kodi 16 Jarvis.
Vypadá to na nějakou změnu na stránkách Playtvaku (asi).
Kodi 17 - Krypton.

**Comment by 72ka** [comment]
Díky, super! Kterou ikonu mám tedy zařadit? Budu teď dělat opravu playtváku, tak bych jí rovnou zařadil. Nicméně SlowTV neovlivním, to jsem nedělal.

**Comment by MarhyCZ** [comment]
Za málo! Všiml jsem si, že existuje i mobilní aplikace playtvák, která má logo velice podobné té mé druhé verzi. Takže klidně můžete zařadit onu "stylizovanou" 
Nevadí, napíšu tam požadavek na tuhle verzi :)

**Comment by 72ka** [comment]
Tak hotovo, vydána opravná verze a je tam ta ikona. Zavírám to tu. Díky, do changelogu jsem vás uvedl jako autora ikony.
