### ISSUE TITLE
nefunkční přehravání videí

### ISSUE THREAD

**Issue by Vasek79** [72ka/plugin.video.dmd-czech.playtvak#5]
Dobrý den,
add-on Playtvak poslední dobou, asi čtrnáct dní nefunguje - nepřehrává videa.
Add-on se spustí, načte se menu, načtou se i názvy a náhledy/obrázky videí, ale po odkliknutí kteréhokoliv videa se po chvíli zobrazí hlášení o chybě. Nejsem zrovna doma, takže log nemám k dipozici. Později mohu dodat...
Podle diskuze na www.xbmc-kodi.cz to nejede ani na Kodi 16 Jarvis.
Vypadá to na nějakou změnu na stránkách Playtvaku (asi).
Kodi 17 - Krypton.

**Comment by 72ka** [comment]
Díky za report. Mrknu na to snad někdy během týdne.




On Fri, Sep 8, 2017 at 9:07 PM +0200, "Vasek79" <notifications@github.com> wrote:












Dobrý den,

add-on Playtvak poslední dobou, asi čtrnáct dní nefunguje - nepřehrává videa.

Add-on se spustí, načte se menu, načtou se i názvy a náhledy/obrázky videí, ale po odkliknutí kteréhokoliv videa se po chvíli zobrazí hlášení o chybě. Nejsem zrovna doma, takže log nemám k dipozici. Později mohu dodat...

Podle diskuze na www.xbmc-kodi.cz to nejede ani na Kodi 16 Jarvis.

Vypadá to na nějakou změnu na stránkách Playtvaku (asi).

Kodi 17 - Krypton.

**Comment by 72ka** [comment]
Tak opraveno, aktualizujte si plugin na 1.0.3.
