### ISSUE TITLE
Video se nespusti

### ISSUE THREAD

**Issue by tydyt** [72ka/plugin.video.dmd-czech.playtvak#7]
Ahoj

Po výběru kvality videa se toto video nespustí. Objeví se hláška, že došlo k chybě přehrávání (doslova "One or more items failed to play. Check the log for more information about this message").
Přikládám debug log (omlouvám se, pokud je toho víc než zdrávo, ale nevěděl jsem, kde přesně začíná sekce s onou chybou)
[debug.txt](https://github.com/72ka/plugin.video.dmd-czech.playtvak/files/1435412/debug.txt)

LibreElec 8.1.2 (64bit) & Kodi Krypton

**Comment by tydyt** [comment]
Hmm, tak teď to funguje (po restartu celého systému). Zřejmě byla chyba mezi klávesnicí a židlí.... Report zavírám.

**Comment by 72ka** [comment]
:D sice rychlej report na Issues, ale příště poprosím opravdu každého nejřív o restart všeho a pak posílat reporty :D ale nic ve zlém. Díky za používání pluginu
